---
#Setup docker

- name: Install docker - arch
  pacman:
    name: "{{ docker_dependencies_arch|default('') }}"
    state: latest
    force: yes
  notify: Restart docker

- name: Create fig alias
  file:
    state: link
    src: "/usr/bin/docker-compose"
    path: "/usr/bin/fig"

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
