---
#Setup docker

- name: Add repository - Centos
  yum_repository:
    name: docker-ce
    description: Docker repo
    baseurl: "{{ docker_repo_rhel }}"
    enabled: true
    gpgcheck: true
  when: ansible_distribution == "CentOS"

- name: Add repository - Rocky
  template:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
    owner: root
    group: root
  when:
    - ansible_distribution == "Rocky"

- name: Install docker - Rhel
  dnf:
    name: "{{ docker_dependencies_rhel|default(omit) }}"
    state: latest
  notify: Restart docker

- name: Configure docker
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: Restart docker

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
