---
#Setup docker

- name: Install docker requirements
  apt:
    name: "{{ docker_dependencies_ubuntu|default('') }}"
    state: latest
    force: yes
  notify: Restart docker

- name: Add docker repo key
  apt_key:
    url: "{{ docker_repo_keyserver }}"
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    mode: 0644

- name: Install docker
  apt:
    name: docker-ce
    state: latest
    force: yes
  notify: Restart docker

- name: Install docker-compose
  apt:
    name: docker-compose
    state: latest

- name: Create fig alias
  file:
    state: link
    src: "/usr/bin/docker-compose"
    path: "/usr/local/bin/fig"

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
